// Generated by CoffeeScript 1.12.6
(function() {
  suite('Stop words', function() {
    var stopwords;
    stopwords = require('../src/stopwords');
    test('exists', function() {
      var s;
      s = stopwords;
      return ok(s);
    });
    test('counts stopwords', function() {
      var data;
      data = stopwords('this is silly', 'en');
      eq(data.wordCount, 3);
      eq(data.stopwordCount, 2);
      return arrayEq(data.stopWords, ['this', 'is']);
    });
    test('strips punctuation', function() {
      var data;
      data = stopwords('this! is?? silly....', 'en');
      eq(data.wordCount, 3);
      eq(data.stopwordCount, 2);
      return arrayEq(data.stopWords, ['this', 'is']);
    });
    test('defaults to english', function() {
      var data;
      data = stopwords('this is fun');
      eq(data.wordCount, 3);
      eq(data.stopwordCount, 2);
      return arrayEq(data.stopWords, ['this', 'is']);
    });
    test('handles spanish', function() {
      var data;
      data = stopwords('este es rico', 'es');
      eq(data.wordCount, 3);
      eq(data.stopwordCount, 2);
      return arrayEq(data.stopWords, ['este', 'es']);
    });
    return test('Safely handles a bad language by falling back to english', function() {
      var data;
      data = stopwords('this is fun', 'fake-language-to-test-fallbacks');
      eq(data.wordCount, 3);
      eq(data.stopwordCount, 2);
      return arrayEq(data.stopWords, ['this', 'is']);
    });
  });

}).call(this);
