// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var _;
  _ = require('lodash');
  module.exports = {
    image: function (doc) {
      var images;
      images = doc('.infobox img');
      if (images.length > 0 && images.first().attr('src'))
        return images.first().attr('src');
    },
    title: function (doc) {
      var titleElement, titleText, usedDelimeter;
      titleElement = doc('title');
      titleText = titleElement.text();
      if (!titleElement)
        return null;
      usedDelimeter = false;
      _.each([
        '|',
        ' - ',
        '\xbb',
        ':'
      ], function (c) {
        var titlePieces;
        if (titleText.indexOf(c) >= 0 && !usedDelimeter) {
          titlePieces = titleText.split(c);
          titleText = titlePieces[0];
          return usedDelimeter = true;
        }
      });
      return titleText.replace(/�/g, '').trim();
    }
  };
}.call(this);
