// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var _, cache, candiateWords, path, removePunctuation, stepwords, stopwords;
  path = require('path');
  _ = require('lodash');
  stepwords = require('../data/stopwords');
  cache = {};
  module.exports = stopwords = function (content, language) {
    var count, overlappingStopwords, stopWords, strippedInput, words;
    if (null == language)
      language = 'en';
    if (cache.hasOwnProperty(language)) {
      stopWords = cache[language];
    } else {
      stopWords = stepwords(language);
      cache[language] = stopWords;
    }
    strippedInput = removePunctuation(content);
    words = candiateWords(strippedInput);
    overlappingStopwords = [];
    count = 0;
    _.each(words, function (w) {
      count += 1;
      if (stopWords.indexOf(w.toLowerCase()) > -1)
        return overlappingStopwords.push(w.toLowerCase());
    });
    return {
      wordCount: count,
      stopwordCount: overlappingStopwords.length,
      stopWords: overlappingStopwords
    };
  };
  removePunctuation = function (content) {
    return content.replace(/[\|\@\<\>\[\]\"\'\.,-\/#\?!$%\^&\*\+;:{}=\-_`~()]/g, '');
  };
  candiateWords = function (strippedInput) {
    return strippedInput.split(' ');
  };
}.call(this);
