// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var replacer, splitter;
  splitter = function () {
  };
  replacer = function () {
  };
  module.exports = [
    splitter,
    replacer
  ];
}.call(this);
